version: '3.4'
services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www
      - ./docker/nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
      - "433:433"
    env_file:
      - variables.env

  php:
    build:
      context: ./
      dockerfile: ./docker/php/php-fpm.docker
    volumes:
      - ./www:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    env_file:
      - variables.env

  php-cli:
    build:
      context: ./
      dockerfile: ./docker/php-cli/php-cli.docker
    volumes:
      - ./www:/var/www
      - ./docker/php-cli/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=localhost

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - variables.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/var/sql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"

